server.port=8082
application.name=pmp

# LOCALE
spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/pmp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=root
spring.datasource.password=AY3@3oiy9fpdzbs
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# LOGGING / GRAYLOG
logging.level.root=INFO
logging.config=classpath:logback-spring.xml
